#!/usr/bin/env python3
"""
Generates the reference pages of the documentation from the files of the plugin, so that they
always match the released version:

    reference/commands.md, reference/permissions.md, reference/config-files.md  (+ fr/ versions)

Sources (folder data/):
    plugin.yml, config.yml, punishments.yml, rewards.yml, announcements.yml, display.yml,
    zones.yml, holograms.yml, emojis.yml, auto_rules.txt   -> copied from the plugin (src/main/resources)
    commands.yml           -> sub-commands, permission checked and texts EN / FR
    permissions-text.yml   -> French texts of the permissions (and English fixes)

Usage, after copying the new files of the plugin in data/:
    pip install pyyaml
    python3 scripts/generate.py
"""
import os
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data')

LANGS = {
    'en': {
        'prefix': '',
        'who': {'everyone': 'Everyone', 'staff': 'Staff', 'admin': 'Admin', 'op': 'Operators', 'nobody': 'Nobody'},
    },
    'fr': {
        'prefix': 'fr',
        'who': {'everyone': 'Tout le monde', 'staff': 'Staff', 'admin': 'Admin', 'op': 'Opérateurs', 'nobody': 'Personne'},
    },
}

GENERATED = '<!-- Generated by scripts/generate.py from the files of the plugin: edit data/ and run the script instead. -->\n'


def load(name):
    with open(os.path.join(DATA, name), encoding='utf-8') as f:
        return yaml.safe_load(f)


def read(name):
    with open(os.path.join(DATA, name), encoding='utf-8') as f:
        return f.read()


def write(lang, path, text):
    folder = os.path.join(ROOT, LANGS[lang]['prefix'], os.path.dirname(path))
    os.makedirs(folder, exist_ok=True)
    with open(os.path.join(folder, os.path.basename(path)), 'w', encoding='utf-8') as f:
        f.write(text)


def cell(text):
    """Plain text in a Markdown table cell: pipes escaped, < > escaped (Vue would read them as tags)."""
    return str(text).replace('|', '\\|').replace('\n', ' ').replace('<', '&lt;').replace('>', '&gt;')


def code(text):
    """Code in a Markdown table cell (the backticks already protect < and >)."""
    return '`' + str(text).replace('|', '\\|').replace('\n', ' ') + '`'


# ------------------------------------------------------------------ permissions


plugin = load('plugin.yml')
permissions = plugin['permissions']
# "2.4.0" -> "2.4": the version named in the introductions of the pages
VERSION = '.'.join(str(plugin['version']).split('.')[:2])
texts = load('permissions-text.yml')


def children(node, seen=None):
    """Every permission given by a node (recursively)."""
    seen = set() if seen is None else seen
    for child, value in (permissions.get(node, {}).get('children') or {}).items():
        if value and child not in seen:
            seen.add(child)
            children(child, seen)
    return seen


STAFF = children('supmod.staff') | {'supmod.staff'}
ADMIN = children('supmod.admin') | {'supmod.admin'}


def who(node):
    default = permissions.get(node, {}).get('default', 'op')
    if default is True or str(default).lower() == 'true':
        return 'everyone'
    # a group gives its children even when their own default is false
    if node in STAFF:
        return 'staff'
    if node in ADMIN:
        return 'admin'
    if default is False or str(default).lower() == 'false':
        return 'nobody'
    return 'op'


def badge(lang, node):
    level = who(node)
    css = {'op': 'admin'}.get(level, level)
    return f'<span class="who {css}">{LANGS[lang]["who"][level]}</span>'


def description(lang, node):
    text = texts.get(node, {})
    if lang == 'fr' and text.get('fr'):
        return text['fr']
    return text.get('en') or permissions.get(node, {}).get('description') or ''


PERMISSION_GROUPS = [
    ('groups', 'Permission groups', 'Groupes de permissions', lambda n: n in ('supmod.*', 'supmod.staff', 'supmod.admin')),
    ('players', 'Players (given to everyone)', 'Joueurs (donné à tout le monde)', lambda n: who(n) == 'everyone'),
    ('punish', 'Punishments', 'Sanctions', lambda n: n.startswith('supmod.punish.')),
    ('support', 'Reports, tickets and appeals', 'Signalements, tickets et appels',
     lambda n: n.startswith(('supmod.admin.report.', 'supmod.ticket.', 'supmod.appeal.')) or n == 'supmod.bypass.report.cooldown'),
    ('staff', 'Staff tools and player files', 'Outils du staff et fiches joueurs',
     lambda n: n.startswith(('supmod.staffmode', 'supmod.vanish', 'supmod.freeze', 'supmod.staffchat', 'supmod.commandspy',
                             'supmod.randomtp', 'supmod.gamemode', 'supmod.player', 'supmod.admin.teleport', 'supmod.admin.spectatortp',
                             'supmod.admin.inventory', 'supmod.notes', 'supmod.tags', 'supmod.watch', 'supmod.timeline', 'supmod.admin.ip'))),
    ('chat', 'Chat and announcements', 'Chat et annonces',
     lambda n: n.startswith(('supmod.chat.', 'supmod.bypass.', 'supmod.admin.chat.', 'supmod.announce.'))
     and n not in ('supmod.bypass.xray', 'supmod.bypass.itemsearch')),
    ('alerts', 'Alerts and AFK', 'Alertes et AFK',
     lambda n: n.startswith(('supmod.alerts.', 'supmod.afk.', 'supmod.health.alerts'))
     or n in ('supmod.bypass.xray', 'supmod.bypass.itemsearch')),
    ('security', 'Security, anti-raid and anti-dupe', 'Sécurité, anti-raid et anti-dupe',
     lambda n: n.startswith(('supmod.verification.', 'supmod.lockdown', 'supmod.security.', 'supmod.blacklist.',
                             'supmod.admin.drops', 'supmod.itemsearch'))),
    ('community', 'Community: ignore, staff list, polls', 'Communauté : ignorer, liste du staff, sondages',
     lambda n: n.startswith(('supmod.ignore', 'supmod.stafflist', 'supmod.staff.listed', 'supmod.poll.'))),
    ('economy', 'Economy and statistics', 'Économie et statistiques',
     lambda n: n.startswith(('supmod.coins.', 'supmod.rewards.', 'supmod.bounty.', 'supmod.stats.', 'supmod.activity',
                             'supmod.staffstats', 'supmod.staff.log'))),
    ('server', 'Server and configuration', 'Serveur et configuration', lambda n: True),
]


def permissions_page(lang):
    fr = lang == 'fr'
    done = set()
    out = [GENERATED]
    if fr:
        out.append('# Permissions\n\n')
        out.append(f'Les **{len(permissions)} permissions** de SupMod, générées depuis le `plugin.yml` du plugin. '
                   'La colonne « Par défaut » indique qui l\'a sans plugin de permissions : '
                   '<span class="who everyone">Tout le monde</span>, les opérateurs via '
                   '<span class="who staff">Staff</span> (`supmod.staff`) ou <span class="who admin">Admin</span> (`supmod.admin`), '
                   'ou <span class="who nobody">Personne</span> (à donner soi-même).\n\n')
        out.append('::: tip Astuce\nCherchez une permission avec la recherche du site (<kbd>Ctrl</kbd> <kbd>K</kbd>). '
                   'Le guide [Permissions et grades](/fr/guide/permissions) propose une configuration LuckPerms prête à copier.\n:::\n\n')
    else:
        out.append('# Permissions\n\n')
        out.append(f'The **{len(permissions)} permissions** of SupMod, generated from the `plugin.yml` of the plugin. '
                   'The "Default" column tells who has it without a permission plugin: '
                   '<span class="who everyone">Everyone</span>, operators through '
                   '<span class="who staff">Staff</span> (`supmod.staff`) or <span class="who admin">Admin</span> (`supmod.admin`), '
                   'or <span class="who nobody">Nobody</span> (give it yourself).\n\n')
        out.append('::: tip\nSearch a permission with the site search (<kbd>Ctrl</kbd> <kbd>K</kbd>). '
                   'The [Permissions and ranks](/guide/permissions) guide has a LuckPerms setup ready to copy.\n:::\n\n')
    for key, en_title, fr_title, match in PERMISSION_GROUPS:
        nodes = [n for n in permissions if n not in done and match(n)]
        if not nodes:
            continue
        done.update(nodes)
        out.append(f'## {fr_title if fr else en_title} {{#{key}}}\n\n')
        out.append('| Permission | ' + ('Par défaut' if fr else 'Default') + ' | Description |\n|---|---|---|\n')
        for node in nodes:
            out.append(f'| {code(node)} | {badge(lang, node)} | {cell(description(lang, node))} |\n')
        out.append('\n')
    return ''.join(out)


# ------------------------------------------------------------------ commands


def commands_page(lang):
    fr = lang == 'fr'
    data = load('commands.yml')
    out = [GENERATED]
    if fr:
        out.append('# Commandes\n\n')
        out.append(f'Toutes les commandes de SupMod {VERSION}, avec la permission vérifiée par le plugin.\n\n')
        out.append('- `<argument>` : obligatoire, `[argument]` : facultatif, `a|b` : au choix.\n')
        out.append('- `/supmod` s\'écrit aussi `/sm`. Toutes les commandes du staff fonctionnent avec la complétion (<kbd>Tab</kbd>).\n')
        out.append('- Durées : `30s`, `10m`, `2h`, `7d`, `2w`, `1mo`, `1y`, combinables (`1d12h`), ou `perm`.\n')
        out.append('- `-s` à la fin d\'une sanction : sanction silencieuse (seul le staff est prévenu).\n\n')
    else:
        out.append('# Commands\n\n')
        out.append(f'Every command of SupMod {VERSION}, with the permission checked by the plugin.\n\n')
        out.append('- `<argument>`: required, `[argument]`: optional, `a|b`: one of them.\n')
        out.append('- `/supmod` can also be written `/sm`. Every staff command has tab completion.\n')
        out.append('- Durations: `30s`, `10m`, `2h`, `7d`, `2w`, `1mo`, `1y`, combinable (`1d12h`), or `perm`.\n')
        out.append('- `-s` at the end of a punishment: silent punishment (only the staff is told).\n\n')
    declared = set(permissions)
    for category in data['categories']:
        out.append(f'## {category[lang]} {{#{category["id"]}}}\n\n')
        out.append(('| Commande | Permission | Description |' if fr else '| Command | Permission | Description |') + '\n|---|---|---|\n')
        for c in category['commands']:
            perm = c.get('perm') or ''
            if perm and perm not in declared:
                print(f'warning: {c["cmd"]} uses {perm}, not declared in plugin.yml', file=sys.stderr)
            perm_cell = f'{code(perm)} {badge(lang, perm)}' if perm else '-'
            out.append(f'| {code(c["cmd"])} | {perm_cell} | {cell(c[lang])} |\n')
        out.append('\n')
    # aliases
    out.append('## Alias {#aliases}\n\n' if fr else '## Aliases {#aliases}\n\n')
    out.append(('| Commande | Alias |' if fr else '| Command | Aliases |') + '\n|---|---|\n')
    for name, info in plugin['commands'].items():
        aliases = info.get('aliases') or []
        if aliases:
            out.append(f'| {code("/" + name)} | {", ".join(code("/" + a) for a in aliases)} |\n')
    out.append('\n')
    out.append('::: tip Conflits avec d\'autres plugins\nSi un autre plugin (EssentialsX...) utilise le même nom, '
               'écrivez la commande avec le préfixe du plugin : `/supmod:gm 1`, `/supmod:vanish`, `/supmod:ignore`.\n:::\n' if fr else
               '::: tip Conflicts with other plugins\nIf another plugin (EssentialsX...) uses the same name, '
               'add the plugin prefix: `/supmod:gm 1`, `/supmod:vanish`, `/supmod:ignore`.\n:::\n')
    return ''.join(out)


# ------------------------------------------------------------------ configuration files

FILES = [
    ('config.yml', 'yaml',
     'Every module of the plugin. Each one has an `enabled` switch.',
     'Tous les modules du plugin. Chacun a un interrupteur `enabled`.'),
    ('punishments.yml', 'yaml',
     'Punishment settings and templates (ladders). Edited in game with `/sm templates`.',
     'Réglages et modèles de sanction (paliers). Modifiable en jeu avec `/sm templates`.'),
    ('display.yml', 'yaml',
     'MOTD, tab, sidebar, boss bars and join messages.',
     'MOTD, tab, barre latérale, barres de boss et messages de connexion.'),
    ('rewards.yml', 'yaml',
     'Play time milestones and daily rewards. Edited in game with `/rewards admin`.',
     'Paliers de temps de jeu et récompenses quotidiennes. Modifiable en jeu avec `/rewards admin`.'),
    ('announcements.yml', 'yaml',
     'Automatic announcements with clickable links. Edited in game with `/sm announce`.',
     'Annonces automatiques avec liens cliquables. Modifiable en jeu avec `/sm announce`.'),
    ('zones.yml', 'yaml',
     'Zones, managed in game with `/sm zones` (empty at the start).',
     'Zones, gérées en jeu avec `/sm zones` (vide au départ).'),
    ('holograms.yml', 'yaml',
     'Holograms, managed in game with `/sm holograms` (empty at the start).',
     'Hologrammes, gérés en jeu avec `/sm holograms` (vide au départ).'),
    ('emojis.yml', 'yaml',
     'Emojis usable in the chat (`chat.emojis` in config.yml).',
     'Emojis utilisables dans le chat (`chat.emojis` dans config.yml).'),
    ('auto_rules.txt', 'text',
     'Rules message sent when a player joins (`auto-rules` in config.yml).',
     'Message de règles envoyé à la connexion (`auto-rules` dans config.yml).'),
]


def config_page(lang):
    fr = lang == 'fr'
    out = [GENERATED]
    if fr:
        out.append('# Fichiers de configuration\n\n')
        out.append(f'Les fichiers par défaut de SupMod {VERSION}, tels que le plugin les crée dans `plugins/SupMod/`. '
                   'Les commentaires des fichiers sont en anglais.\n\n')
        out.append('::: tip Vous n\'êtes pas obligé d\'ouvrir ces fichiers\nPresque tout se règle en jeu avec `/sm settings`. '
                   'À chaque mise à jour, les nouvelles options sont ajoutées automatiquement sans toucher à vos valeurs.\n:::\n\n')
        out.append('| Fichier | Contenu |\n|---|---|\n')
    else:
        out.append('# Configuration files\n\n')
        out.append(f'The default files of SupMod {VERSION}, as the plugin creates them in `plugins/SupMod/`.\n\n')
        out.append('::: tip You don\'t have to open these files\nAlmost everything can be changed in game with `/sm settings`. '
                   'At each update, the new options are added automatically and your values are kept.\n:::\n\n')
        out.append('| File | Content |\n|---|---|\n')
    for name, _, en, fr_text in FILES:
        anchor = name.replace('.', '-').replace('_', '-')
        out.append(f'| [{code(name)}](#{anchor}) | {cell(fr_text if fr else en)} |\n')
    out.append('| `lang/en_US.yml`, `lang/fr_FR.yml` | ' +
               ('Tous les messages et textes des menus, voir [Langues et messages](/fr/guide/languages). |\n\n' if fr else
                'Every message and menu text, see [Languages and messages](/guide/languages). |\n\n'))
    for name, syntax, en, fr_text in FILES:
        anchor = name.replace('.', '-').replace('_', '-')
        out.append(f'## {name} {{#{anchor}}}\n\n{fr_text if fr else en}\n\n')
        body = read(name).rstrip('\n')
        fence = '````' if '```' in body else '```'
        if name != 'config.yml':
            out.append('::: details ' + ('Afficher le fichier' if fr else 'Show the file') + '\n\n')
        out.append(f'{fence}{syntax}\n{body}\n{fence}\n\n')
        if name != 'config.yml':
            out.append(':::\n\n')
    return ''.join(out)


def main():
    for lang in LANGS:
        write(lang, 'reference/commands.md', commands_page(lang))
        write(lang, 'reference/permissions.md', permissions_page(lang))
        write(lang, 'reference/config-files.md', config_page(lang))
    print('reference pages generated')


if __name__ == '__main__':
    main()
